name: DEMO CREATE ACCOUNT

on: 
  workflow_dispatch:
    inputs:
      port_payload:
        required: true
        description: Port's payload, including details for who triggered the action and general context (blueprint, run id, etc...)
        type: string

jobs:
  demo-create-account:
    runs-on: ubuntu-latest
    env:
      ACCOUNT_NAME: aws-c2-${{fromJson(inputs.port_payload).payload.properties.solution_name}}-${{fromJson(inputs.port_payload).payload.properties.sdlc}}
      ACCOUNT_EMAIL: accounts+${{fromJson(inputs.port_payload).payload.properties.account_name}}@nuvibit.com
      SDLC: ${{fromJson(inputs.port_payload).payload.properties.sdlc}}
      COST_CENTER: ${{fromJson(inputs.port_payload).payload.properties.cost_center_id}}
      SECURITY_CONTACT_EMAIL: ${{fromJson(inputs.port_payload).payload.properties.security_contact_email}}
      PORT_USER_EMAIL: ${{fromJson(inputs.port_payload).trigger.by.user.email}}
      PORT_USER_FIRST_NAME: ${{fromJson(inputs.port_payload).trigger.by.user.firstName}}
      PORT_USER_LAST_NAME: ${{fromJson(inputs.port_payload).trigger.by.user.lastName}}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Update Account List
        run: |
          account_list_path="account_list.json"
          account_list=$(cat account_list.json)
          new_account=$(cat <<EOF 
          {
              "account_name": "$ACCOUNT_NAME",
              "account_email": "$ACCOUNT_EMAIL",
              "ou_path": "/root/solutions/$SDLC",
              "close_on_deletion": true,
              "account_tags": {
                  "AccountOwner": "$PORT_USER_EMAIL",
                  "AccountType": "workload",
                  "AccountDescription": "This is a demo account",
                  "CostCenter": "$COST_CENTER"
              },
              "alternate_contacts": [
                  {
                      "type": "SECURITY",
                      "name": "Security Contact",
                      "email_address": "$SECURITY_CONTACT_EMAIL"
                  }
              ]
          }
          EOF)
          new_account_list=$(echo "$account_list" | jq --argjson newAcc "$new_account" '. += [$newAcc]')
          echo "$new_account_list" > $account_list_path

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "adding new aws account '${{fromJson(inputs.port_payload).payload.properties.account_name}}'"
          committer: GitHub <noreply@github.com>
          author: ${{env.PORT_USER_FIRST_NAME}} ${{env.PORT_USER_LAST_NAME}} <${{env.PORT_USER_EMAIL}}>
          title: "port: create aws account '${{env.ACCOUNT_NAME}}'"
          labels: Demo
          add-paths: account_list.json
          branch: demo-create-account
          branch-suffix: short-commit-hash
          delete-branch: true
          reviewers: stefano-franco